module.exports = [
    {color: 'red', suit: 'diamond', value: 2, imageName: '2_of_diamonds'},
    {color: 'red', suit: 'diamond', value: 3, imageName: '3_of_diamonds'},
    {color: 'red', suit: 'diamond', value: 4, imageName: '4_of_diamonds'},
    {color: 'red', suit: 'diamond', value: 5, imageName: '5_of_diamonds'},
    {color: 'red', suit: 'diamond', value: 6, imageName: '6_of_diamonds'},
    {color: 'red', suit: 'diamond', value: 7, imageName: '7_of_diamonds'},
    {color: 'red', suit: 'diamond', value: 8, imageName: '8_of_diamonds'},
    {color: 'red', suit: 'diamond', value: 9, imageName: '9_of_diamonds'},
    {color: 'red', suit: 'diamond', value: 10, imageName: '10_of_diamonds'},
    {color: 'red', suit: 'diamond', value: 10, imageName: 'jack_of_diamonds2'},
    {color: 'red', suit: 'diamond', value: 10, imageName: 'queen_of_diamonds2'},
    {color: 'red', suit: 'diamond', value: 10, imageName: 'king_of_diamonds2'},
    {color: 'red', suit: 'diamond', value: 11, imageName: 'ace_of_diamonds'},

    {color: 'red', suit: 'heart', value: 2, imageName: '2_of_hearts'},
    {color: 'red', suit: 'heart', value: 3, imageName: '3_of_hearts'},
    {color: 'red', suit: 'heart', value: 4, imageName: '4_of_hearts'},
    {color: 'red', suit: 'heart', value: 5, imageName: '5_of_hearts'},
    {color: 'red', suit: 'heart', value: 6, imageName: '6_of_hearts'},
    {color: 'red', suit: 'heart', value: 7, imageName: '7_of_hearts'},
    {color: 'red', suit: 'heart', value: 8, imageName: '8_of_hearts'},
    {color: 'red', suit: 'heart', value: 9, imageName: '9_of_hearts'},
    {color: 'red', suit: 'heart', value: 10, imageName: '10_of_hearts'},
    {color: 'red', suit: 'heart', value: 10, imageName: 'jack_of_hearts2'},
    {color: 'red', suit: 'heart', value: 10, imageName: 'queen_of_hearts2'},
    {color: 'red', suit: 'heart', value: 10, imageName: 'king_of_hearts2'},
    {color: 'red', suit: 'heart', value: 11, imageName: 'ace_of_hearts'},

    {color: 'black', suit: 'spade', value: 2, imageName: '2_of_spades'},
    {color: 'black', suit: 'spade', value: 3, imageName: '3_of_spades'},
    {color: 'black', suit: 'spade', value: 4, imageName: '4_of_spades'},
    {color: 'black', suit: 'spade', value: 5, imageName: '5_of_spades'},
    {color: 'black', suit: 'spade', value: 6, imageName: '6_of_spades'},
    {color: 'black', suit: 'spade', value: 7, imageName: '7_of_spades'},
    {color: 'black', suit: 'spade', value: 8, imageName: '8_of_spades'},
    {color: 'black', suit: 'spade', value: 9, imageName: '9_of_spades'},
    {color: 'black', suit: 'spade', value: 10, imageName: '10_of_spades'},
    {color: 'black', suit: 'spade', value: 10, imageName: 'jack_of_spades2'},
    {color: 'black', suit: 'spade', value: 10, imageName: 'queen_of_spades2'},
    {color: 'black', suit: 'spade', value: 10, imageName: 'king_of_spades2'},
    {color: 'black', suit: 'spade', value: 11, imageName: 'ace_of_spades2'},

    {color: 'black', suit: 'club', value: 2, imageName: '2_of_clubs'},
    {color: 'black', suit: 'club', value: 3, imageName: '3_of_clubs'},
    {color: 'black', suit: 'club', value: 4, imageName: '4_of_clubs'},
    {color: 'black', suit: 'club', value: 5, imageName: '5_of_clubs'},
    {color: 'black', suit: 'club', value: 6, imageName: '6_of_clubs'},
    {color: 'black', suit: 'club', value: 7, imageName: '7_of_clubs'},
    {color: 'black', suit: 'club', value: 8, imageName: '8_of_clubs'},
    {color: 'black', suit: 'club', value: 9, imageName: '9_of_clubs'},
    {color: 'black', suit: 'club', value: 10, imageName: '10_of_clubs'},
    {color: 'black', suit: 'club', value: 10, imageName: 'jack_of_clubs2'},
    {color: 'black', suit: 'club', value: 10, imageName: 'queen_of_clubs2'},
    {color: 'black', suit: 'club', value: 10, imageName: 'king_of_clubs2'},
    {color: 'black', suit: 'club', value: 11, imageName: 'ace_of_clubs'}
]